### ISSUE TITLE
Code cleanup needed

### ISSUE THREAD

**Issue by batchu** [PerfectoMobileSA/PerfectoSampleProject#2]
Can you please clean up the source code?
Eg: catching a global exception, using Sys.out instead of a Logging framework, Functions violating the single responsibility principle etc.
https://github.com/PerfectoMobileSA/PerfectoSampleProject/blob/b93910c994c842a8a9027870031de31d5cf6157f/src/main/java/com/perfecto/sampleproject/PerfectoSelenium.java#L75

**Comment by genesisthomas** [comment]
Dear @batchu , Thanks for your comments. This was intended to be a sample project but anyways we have changed the code base to throw the exception and remove unwanted sys outs.
